### ISSUE TITLE
function st_asmvt(unknown, integer, unknown, record) does not exist

### ISSUE THREAD

**Issue by nibygro** [Geodan/postgis-mvt-server#10]
Hi. I trying to use this server, but unfortenutely got the follwing error:

> Error executing database query: function st_asmvt(unknown, integer, unknown, record) does not exist error: function st_asmvt(unknown, integer, unknown, record) does not exist
>     at Connection.parseE (/home/bulaj/projects/postgis-mvt-server/node_modules/pg/lib/connection.js:567:11)
>     at Connection.parseMessage (/home/bulaj/projects/postgis-mvt-server/node_modules/pg/lib/connection.js:391:17)
>     at Socket.<anonymous> (/home/bulaj/projects/postgis-mvt-server/node_modules/pg/lib/connection.js:129:22)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at readableAddChunk (_stream_readable.js:176:18)
>     at Socket.Readable.push (_stream_readable.js:134:10)
>     at TCP.onread (net.js:547:20)

What can be wrong? Pg 10 + PostGIS 2.4

> # SELECT PostGIS_full_version();
>                                                                                      
>  POSTGIS="2.4.1 r16012" PGSQL="100" GEOS="3.6.0-CAPI-1.10.0 r0" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.2.2, released 2017/09/15" LIBXML="2.9.3" LIBJSON="0.11.99" LIBPROTOBUF="1.2.1" TOPOLOGY RASTER
> (1 row)

**Comment by RubioV** [comment]
Hi Nikolai,

Could you check if the ST_AsMVT and ST_AsMVTGeom functions are loaded in PostGIS?
select * from pg_proc where proname like 'st_asmvt' or proname like 'st_asmvtgeom';

Regards
Rubio

**Comment by RubioV** [comment]
Hi Nikolai,

This problem was likely due to a recent change in the ST_AsMVT syntax (sequence of parameters was changed in PostGIS commit https://github.com/postgis/postgis/commit/bbb8e0ea4592cc8db1b41f581f7a723d04f7935e). This should now be fixed in https://github.com/Geodan/postgis-mvt-server/commit/2e87d58c3141b1f6ad66acec59670eb9ad8ce695.

Regards
Rubio
